redpanda-data/seastar

- scripts/addr2line.py
- scripts/seastar-addr2line
Commits related to decoding the kernel backtraces into symbols. The commit messages contain more detail.
> Support kernel trace decoding in seastar-addr2line

- src/core/reactor_backend.cc
The existing assert that was introduced in
528762adbaf2c6dde857957b920606378959e8fb
is too harsh.  It will fail on the first retry
failure after `needs_preeempt` returned true.
This lead to the following crash:
```
scylla: ./seastar/src/core/reactor_backend.cc:286: size_t seastar::aio_general_context::flush(): Assertion `retried != begin' failed.
```
Decoded backtrace:
```
seastar::aio_general_context::flush() at ./build/release/seastar/./seastar/src/core/reactor_backend.cc:286
(inlined by) seastar::reactor_backend_aio::wait_and_process_events(__sigset_t const*) at ./build/release/seastar/./seastar/src/core/reactor_backend.cc:489
seastar::reactor::sleep() at ./build/release/seastar/./seastar/src/core/reactor.cc:3041
(inlined by) seastar::reactor::do_run() at …
```
> [v23.1.x] Backport pr1233: aio_general_context: flush: provide 1 second grace for retries

- src/core/reactor_backend.cc
The existing assert that was introduced in
528762adbaf2c6dde857957b920606378959e8fb
is too harsh.  It will fail on the first retry
failure after `needs_preeempt` returned true.
This lead to the following crash:
```
scylla: ./seastar/src/core/reactor_backend.cc:286: size_t seastar::aio_general_context::flush(): Assertion `retried != begin' failed.
```
Decoded backtrace:
```
seastar::aio_general_context::flush() at ./build/release/seastar/./seastar/src/core/reactor_backend.cc:286
(inlined by) seastar::reactor_backend_aio::wait_and_process_events(__sigset_t const*) at ./build/release/seastar/./seastar/src/core/reactor_backend.cc:489
seastar::reactor::sleep() at ./build/release/seastar/./seastar/src/core/reactor.cc:3041
(inlined by) seastar::reactor::do_run() at …
```
> [v22.3.x] Backport pr1233: aio_general_context: flush: provide 1 second grace for retries

- CMakeLists.txt
- include/seastar/core/circular_buffer_fixed_capacity.hh
- include/seastar/core/internal/cpu_profiler.hh
- include/seastar/core/internal/stall_detector.hh
- include/seastar/core/internal/timers.hh
- include/seastar/core/reactor.hh
- include/seastar/core/reactor_config.hh
- src/core/cpu_profiler.cc
- src/core/reactor.cc
- tests/unit/CMakeLists.txt
- tests/unit/cpu_profiler_test.cc
- tests/unit/stall_detector_test.cc
- tests/unit/stall_detector_test_utilities.hh
A basic CPU profiler implementation based on `libunwind` and `perf_event_open`(when available).
> CPU profiler implementation

- include/seastar/util/sampler.hh
- src/core/memory.cc
- tests/unit/alloc_test.cc
Details in individual changes.
> Allocator optimizations

- include/seastar/core/internal/cpu_profiler.hh
- src/core/cpu_profiler.cc
- tests/unit/CMakeLists.txt
- tests/unit/cpu_profiler_alloc_test.cc
- tests/unit/cpu_profiler_test.cc
Fixes https://github.com/redpanda-data/redpanda/issues/12901
> CPU profiler fixes

- include/seastar/core/io_queue.hh
- src/core/reactor.cc
This is needed to implement throttling in tiered-storage.
> Expose bandwidth in queue configuration

- src/core/reactor_backend.cc
- src/core/reactor_backend.hh
- src/net/tls.cc
Backports:
- https://github.com/redpanda-data/seastar/pull/88
- https://github.com/redpanda-data/seastar/pull/87
> [v23.2.x] Various backports

- CMakeLists.txt
- demos/CMakeLists.txt
- include/seastar/net/tcp.hh
- src/net/ossl.cc
- src/seastar.cc
- src/websocket/server.cc
- tests/unit/CMakeLists.txt
- tests/unit/tls_test.cc
Conditionally exclude GnuTLS from build when using OpenSSL
> CORE-3102 Conditionally exclude GnuTLS

- src/net/ossl.cc
- tests/unit/loopback_socket.hh
A BIO in OpenSSL is a "Basic I/O" abstraction structure that is used to move data.  For our purposes, we will construct a BIO that can interact with a TLS session to push data onto the output socket, or wait for data to arrive on the input socket.
This reduces the number of copies being performed.
> CORE-24 custom bio

- include/seastar/json/formatter.hh
- tests/unit/httpd_test.cc
- tests/unit/json_formatter_test.cc
Downstream https://github.com/scylladb/seastar/pull/2287
> Downstream json improvements

- include/seastar/json/formatter.hh
- tests/unit/httpd_test.cc
- tests/unit/json_formatter_test.cc
Downstream https://github.com/scylladb/seastar/pull/2287
> [v24.1.x] Downstream json improvements

- include/seastar/json/formatter.hh
- tests/unit/httpd_test.cc
- tests/unit/json_formatter_test.cc
Downstream https://github.com/scylladb/seastar/pull/2287
> [v23.3.x] Downstream json improvements

- src/core/metrics.cc
Downstream https://github.com/scylladb/seastar/pull/2346
> metrics: Use this_shard_id unconditionally

- src/net/ossl.cc
Once the shutdown alert is sent, if anymore data is received on the SSL session, the SSL_shutdown method will return
SSL_R_APPLICATION_DATA_AFTER_CLOSE_NOTIFY error code.  This may be due to a race condition where data is received immediately after the close notify is sent.  In this situation, we will simply ignore the error and continue shutdown.
Added the drain_openssl_error_stack method that will purposefully empty out OpenSSL's error stack in situations where errors can be safely ignored.
> net/tls: Handling app data post shutdown

- src/core/prometheus.cc
- tests/unit/CMakeLists.txt
- tests/unit/prometheus_test.cc
Backport of https://github.com/redpanda-data/seastar/pull/136 and https://github.com/redpanda-data/seastar/pull/139
> [v24.1.x] CORE-6859 prometheus: sanitize label value for text protocol

- src/core/prometheus.cc
- tests/unit/CMakeLists.txt
- tests/unit/prometheus_test.cc
Backport of https://github.com/redpanda-data/seastar/pull/136 and https://github.com/redpanda-data/seastar/pull/139
> [v23.3.x] CORE-6859 prometheus: sanitize label value for text protocol

- src/net/ossl.cc
This PR adds support for TLS session resumption in the OpenSSL implementation.
> CORE-7098: net/tls: Added session resumption implementation to OpenSSL

- src/net/tls.cc
Cherry pick commit 5e9b43ae3d23131502b415c7f30ee94e5c3cbfac from upstream
> CORE-7254 tls: clear session ticket before releasing

- include/seastar/json/formatter.hh
- tests/unit/json_formatter_test.cc
Downstream https://github.com/scylladb/seastar/pull/2440
> Downstream more json improvements

- include/seastar/util/backtrace.hh
- src/util/backtrace.cc
This brings https://github.com/scylladb/seastar/commit/3133ecdd6599469672f1d7cbffdd92606f2b132c into our fork. 
This is needed for memory_sampling_tests to pass in bazel, where the size of the stack trace is larger. It has knock-on benefits of reducing the chance of allocation in low-memory situations as described in the commit above.
See CORE-7598.
> util/backtrace: Optimize formatter to reduce memory allocation overhead

- tests/unit/cpu_profiler_test.cc
This test fails often in GHA. Identical failures are difficult to reproduce locally, but other local failures are easy to repro by using something like `taskset -c 0,1 stress -c 2` while running the tests.
Introduce "loose mode" in the test, enabled by default, which looses some of the checks by a large amount.
Test this by running the test 100 times in CI in another PR.
> cpu_profiler: deflake cpu_profiler_test

- tests/unit/cpu_profiler_test.cc
Only test changes (deflake cpu_profiler_test).
> Backport green CI fixes to 24.3

- .github/workflows/tests.yaml
- tests/unit/cpu_profiler_test.cc
Only test/CI files modified in this change.
> Backport green CI fixes to 25.1

- src/core/reactor.cc
- tests/unit/stall_detector_test.cc
Backport the 3 changes from https://github.com/redpanda-data/seastar/pull/200.
> Backport stall SEGV fixes to 24.2

- src/core/reactor.cc
- tests/unit/stall_detector_test.cc
Backport the 3 changes from https://github.com/redpanda-data/seastar/pull/200.
> Backport stall SEGV fixes to 25.1

- include/seastar/util/backtrace.hh
- src/core/reactor.cc
Backport of https://github.com/redpanda-data/seastar/pull/207
> [25.1.x] Backport: Print incrementally in sigsegv handler

- include/seastar/core/memory.hh
- src/core/memory.cc
- tests/unit/alloc_test.cc
Add a scoped_system_alloc_fallback object, which changes the behavior when at least one of these objects is in scope: when an allocation would otherwise fail, we instead fall back to the system allocator.
This would allow limited use of the system allocator in cases where it is useful to do large allocations, which might otherwise fail due to fragmentation.
> Add scoped to fallback to system alloc
