redpanda-data/seastar

include/seastar/core/rwlock.hh

Adding fixes to our pending for_upstream branch.

rwlock: pass timeout parameter to get_units

---

include/seastar/core/coroutine.hh

The syntax is not legal. gcc 10.2.0 accepts it, but 10.2.1 rejects it.
Signed-off-by: Ben Pope <ben@vectorized.io>

coroutine: further restrict future<void> case for gcc >= 10.2.1

---

include/seastar/http/httpd.hh
include/seastar/http/request.hh
src/http/httpd.cc

Added per listener TLS setup (fixed recognizing protocol schema) and ability to recognize which listener accepted given connection. This feature is needed for the Kafka-Rest compatibility proxy in redpanda as we need to return a contextual information based on HTTP or HTTPS as per the protocol description and need underlying access to the actual listener information.

Httpd request context

---

include/seastar/http/reply.hh
src/http/reply.cc

Adding `409 Conflict` status
A 409 can be returned when a POST is received for an object that already exists (https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto#L80).
For example a request to `v1/security/users` to create an existing user would return a 409. The following commit on the redpanda side would do this: https://github.com/dimitriscruz/redpanda/commit/cb9562c1bac3b409deeda9efb0ff378bf55dbc6d
Eventually, the 409 code would be used by the k8s operator to detect the existence of a user and stop trying to create one without having to do a GET or parse the returned message.
Note: I'm creating this PR against branch `httpd` because it is the one used when compiling redpanda (3rd party - vtools/cmake/3rdparty.cmake.in). The `master` branch does not work with …

httpd: add status_type 409

---

include/seastar/core/fair_queue.hh
src/core/fair_queue.cc

This is the near-term fix for hanging IOs under heavy load.  The switch from uint32_t to uint64_t should be cheap on modern x86_64 processors, but may be more expensive on other archs (I'm not sure what the deal is with the various ARM archs and 8 byte atomics).
---
When uint32_t offsets were used here, the frequent
integer wrapping caused queues to get stuck.  The _pending
tail values would compare as greater than the head values
forever if there weren't always new requests coming through
to wrap the head/tail pointers again.
Signed-off-by: John Spray <jcs@vectorized.io>

core: use 64 bit head+tail pointers in fair_queue

---

include/seastar/http/exception.hh

There are various 3xx statuses we might want instead
of the default 301.
Signed-off-by: John Spray <jcs@vectorized.io>

http: permit custom status on redirect_exception

---

src/http/routes.cc

Previously this was only handled from synchronous
code inside a handler, not when thrown from inside
the future returned by the handler.
Signed-off-by: John Spray <jcs@vectorized.io>

http: make redirect_exception work from inside futures

---

include/seastar/http/exception.hh
include/seastar/http/httpd.hh
src/http/httpd.cc
src/http/routes.cc

In JSON request handlers, the string carried in the exception would be wrapped in a {"message": <string>, "status": <code>} body.  That prevented sending back a full response body to provide structured errors, e.g. dicts of request attributes to validation issues.
In this PR, a content_type field is added to base_exception, and if this content type is set then the exception's string is used as the full response body, and the response's content type header is set.

http: add ability to pass response bodies in `base_exception`

---

include/seastar/core/sleep.hh
src/core/future-util.cc
tests/unit/abort_source_test.cc

This is useful for unit testing classes which use
sleep_abortable: all the types work, we just
weren't creating the symbol in the .cc file.
Signed-off-by: John Spray <jcs@redpanda.com>

core: add sleep_abortable instantiation for manual_clock

---

scripts/addr2line.py
scripts/seastar-addr2line

Prior to this change the addr2line.py script always uses addr2line as the
binary to decode stack frames. This change allows the path and/or name
of the binary to be provided explicitly on the command line.
This allows the of llvm-addr2line, an alternative implementation
based on llvm-symbolizer, which in my experiments is over *200* times as
fast as addr2line in decoding some redpanda stack traces.
See https://sourceware.org/bugzilla/show_bug.cgi?id=29010 for more
on the addr2line slowness.
This change also slightly changes the 'dummy line' strategy used to
detect when addr2line has finished outputting frames for the current
address to make it compatible with llvm-addr2line.
Fixes #1035.

Allow use of llvm-addr2line as the command

---

include/seastar/core/metrics.hh
include/seastar/core/metrics_api.hh
src/core/metrics.cc
src/core/prometheus.cc

This PR contains a set of patches from the seastar mailing list ([patch set](https://groups.google.com/u/0/g/seastar-dev/c/qrlkP5y8JXw) and [repo](https://github.com/amnonh/seastar/tree/metrics_summary)). They add aggregations
support to the seastar metrics subsystem. This PR used to be based on an older version of the upstream patch set,
but Ben fed back our findings and the new version matches our needs as is.
Motivation:
Histograms are the Prometheus killer. They are big to send over the
network and are big to store in Prometheus.
Histograms' size is always an issue, but with Seastar, it becomes even trickier.
Typically, each shard would collect its histograms, so the overall data
is multiplied by the number of shards.
This series addresses the need to report quantile information like …

Add metrics aggregation capabilities

---

include/seastar/core/metrics_api.hh
include/seastar/core/metrics_registration.hh
include/seastar/core/prometheus.hh
include/seastar/core/scollectd.hh
src/core/io_queue.cc
src/core/metrics.cc
src/core/prometheus.cc
src/core/reactor.cc
src/core/scollectd.cc

Previously, seastar collected all metrics (and metrics related metadata) in a single object (`metrics::impl::impl`). The consequence of this is that there was no way to have multiple metrics namespaces and expose each namespace through its own prometheus endpoint. If an application published a large volume of metrics, the user had to filter them by using by using the `name` request parameter of the prometheus endpoint. The downside of this approach is that the user must have knowledge of the metrics set and, even in that case,  some queries cannot be expressed in terms of substring matching (i.e. the existing filtering implementation).
A more flexible approach is to allow applications to categorise metrics at the time of registering them and expose the different metrics set on different …

Allow for multiple metrics endpoints

---

include/seastar/core/metrics_api.hh
src/core/metrics.cc
tests/unit/CMakeLists.txt
tests/unit/metric_family_replication_test.cc

This PR extends the seastar metrics sub-system with the ability to replicate metric families across different internal metric
implementation (for more context see #25).
Our use case for this change is to expose a selection of internal seastar metrics on the new metrics endpoint, "/public_metrics".
Seastar metrics are registered on the default metric implementation (not the one driving "/public_metrics"), so we need a way
of registering certain seastar metrics on an internal implementation of our choice. The alternative to what this PR proposes
is to make the data required for the desired metrics available via seastar public APIs, but that's more intrusive and the registration
would lead to some involved code in Redpanda.
Each `metrics::impl` (internal implementation) object stores a set …

Metric replication accross internal implementations

---

include/seastar/core/metrics.hh
include/seastar/core/metrics_api.hh
src/core/metrics.cc

This PR updates the 'metric_groups::clear` method to retain the same metrics implementation after the call.

Use the same internal implementation after clear

---

src/core/memory.cc

Currently the seastar_memory logger is only created when
SEASTAR_DEFAULT_ALLOCATOR is undefined, i.e., when the seastar
allocator is being used. That makes sense in that this logger is only
ever used to emit diagnostics by the seastar allocator.
However, it means that seastar applications which try to adjust the
seastar logger level on the command line will fail because this logger
does not exist. So you have to handle this command line argument
differnetly in release and debug builds.
A more forgiving approach is to allow setting the level of this logger
regardless of the build type. After all, it is valid to set the level of a
loggeer that happens not to log anything for a particular run. This only
takes this a bit further since the logger will *never* log anything in
debug builds.
To …

Create the seastar_memory logger in all builds

---

include/seastar/core/scheduling.hh
src/core/reactor.cc

This PR extends the public interface of scheduling_group to expose
usage statistics (e.g. runtime).

scheduling_group: expose usage statistics

---

src/net/dns.cc
tests/unit/dns_test.cc

Fixes #1244
Iff a TCP mode ARES socket connection fails, we don't get a socket in the socket struct for the virtual fd. As the connect function cannot fail at this point (engine::connect completion), we can only set all poll flags and wake up the select emulation we are running.
Here we expect to detect the error in the upcoming sendv call, we however do not check this field being fully initialized -> crash.
Simple fix,. just verify field, if not inited, return ENOTCONN.
(cherry picked from commit 1d9f3306bb04fba7337550037b2140c1600139f2)

dns: Handle TCP mode connect failure

---

include/seastar/core/memory.hh
src/core/memory.cc
src/core/reactor.cc
tests/unit/alloc_test.cc

This metric counts the number of times an allocation request
could not be satisfied even after reclaim, and a nullptr/bad_alloc
was returned/thrown.

Add allocation failure metric to memory metrics

---

src/net/dns.cc

The problem with DNS queries is caused by the fact that the UDP socket
is used concurrently i.e. write is scheduled while the other one is
pending.
DNS queries are based on c-ares library. The library is initialized with
a set of functions (callbacks) that are called whenever there is a need
to send, receive, create socket, connect or close.
Fixed processing of send requests leading to assertion being triggered
in reactor.
The fix involves checking if send is already pending and if so returning
an error. The error returned from send callback will instruct c-ares
library to retry the query.

Fixed concurrent socket access in `dns_resolve`

---

include/seastar/http/request.hh
src/http/httpd.cc

These changes were added between our v22.2.x and v22.3.x seastar branches, and cause dropped connections from `urllib` clients that use Connection: close, including ansible.
This doesn't exactly fix whatever the bug is, but reverts to the old behavior where "close" headers from urllib were ignored, which worked in practice.
Related: https://github.com/redpanda-data/redpanda/issues/8020

[v22.3.x] httpd: revert `Connection` header handling changes

---

include/seastar/core/abort_source.hh
tests/unit/abort_source_test.cc

calling `node_algorithms::unlink(this_ptr())` with an engaged subscription results in use-after-free that is reproduced by the added unit test.
Fixes #1336
Signed-off-by: Benny Halevy <bhalevy@scylladb.com>

abort_source: move-assign operator: call base class unlink

---

include/seastar/core/semaphore.hh
tests/unit/semaphore_test.cc

semaphore_units keeps a pointer to the semaphore
soe if the semaphore is moved and/or destroyed
destroying the sempahore_units will caused
use-after-move or use-after-free.
This change adds _outstanding_units counter member to basic_semaphore and manages it in semaphore_units. semaphore move constructor then asserts that
o._outstanding_units == 0 when moved.
Add a unit test to semaphore_test to cover this case.
Refs #1323
Cherry-picked from [3061b2](https://github.com/scylladb/seastar/commit/3061b2f53a9a89596786763db03e3ae44398d33c)
Signed-off-by: Benny Halevy <bhalevy@scylladb.com>

semaphore: assert no outstanding units when moved

---

include/seastar/core/iostream-impl.hh

Previously, do_flush would skip calling flush
on the underlying _fd if _end==0.
If the semantics of flush are "flush data, all the way to the underlying file" then this is incorrect, because in the slow_write path we may set _end=0 and call through to put() immediately: this leaves output_stream in a state where the next call to flush() does nothing, but the underlying data_sink (for example file_data_sink_impl) has a writebehind operation in flight.
If the output stream is then dropped, we may crash when the underlying fd's write behind op tries
to complete.
One can work around this by closing the output_stream instead of just flushing it, but this doesn't fit if the caller wants to keep their file object open beyond the lifetime of the output stream.

iostream: always flush _fd in do_flush

---

src/core/reactor_backend.cc

The existing assert that was introduced in
528762adbaf2c6dde857957b920606378959e8fb
is too harsh.  It will fail on the first retry
failure after `needs_preeempt` returned true.
This lead to the following crash:
```
scylla: ./seastar/src/core/reactor_backend.cc:286: size_t seastar::aio_general_context::flush(): Assertion `retried != begin' failed.
```
Decoded backtrace:
```
seastar::aio_general_context::flush() at ./build/release/seastar/./seastar/src/core/reactor_backend.cc:286
(inlined by) seastar::reactor_backend_aio::wait_and_process_events(__sigset_t const*) at ./build/release/seastar/./seastar/src/core/reactor_backend.cc:489
seastar::reactor::sleep() at ./build/release/seastar/./seastar/src/core/reactor.cc:3041
(inlined by) seastar::reactor::do_run() at …
```

[v22.2.x] Backport pr1233: aio_general_context: flush: provide 1 second grace for retries

---

src/http/client.cc

Redpanda uses this logger name for its http client and we choose to change the logger name in Seastar to avoid duplicate logger registration exceptions.

http: rename http client logger

---

include/seastar/core/chunked_fifo.hh
tests/unit/chunked_fifo_test.cc

Need to be using `basic_iterator<const T>`
rather than `basic_iterator<T>`
Otherwise, we get the following compilation error:
```
/home/bhalevy/dev/seastar/include/seastar/core/chunked_fifo.hh:164:15: error: using declaration refers into 'basic_iterator<int>::', which is not a base class of 'const_iterator'
using basic_iterator<T>::basic_iterator;
^~~~~~~~~~~~~~~~~~~
```
Added a unit test that doesn't build without the fix.
Signed-off-by: Benny Halevy <bhalevy@scylladb.com>
(cherry picked from commit 6e48abed8e9b068270d90160cafd137d9c85af17)

[v23.1.x] chunked_fifo: const_iterator: use the base class ctor

---

NOTICE
include/seastar/core/memory.hh
include/seastar/core/reactor_config.hh
include/seastar/util/backtrace.hh
include/seastar/util/sampler.hh
src/core/memory.cc
src/core/reactor.cc
tests/perf/CMakeLists.txt
tests/perf/allocator_perf.cc
tests/unit/CMakeLists.txt
tests/unit/alloc_test.cc

As discussed this is the current state:
Commits should stand on their own. The most interesting ones are probably "use sampler" and "use separate pool" which implement the meat. 
It's not optimized yet to the last instruction as that will require reshuffling a bit of code but I first want to confirm we are happy with the general approach for a v1.
I am using this with https://github.com/redpanda-data/redpanda/compare/dev...StephanDollberg:redpanda:support-mem-profiling?expand=1 (seastar change not committed there):
I am using OMB benchrunner using this config: https://gist.github.com/StephanDollberg/3d51e3ea029708f7aed49a277220cb26 I am happy to try other ones if you think they are more fitting.
These are the last lines of three different runs each:
current dev:
```
[client 0:0] …
```

Sampling heap profiler 

---

src/core/reactor.cc

Two minor opts in the reactor main loop:
- Use lambda type not `std::function` for `check_work`
- Use `ss::noncopyable_function` for `pure_check_work`
See commit messages for details on the individual changes.
It's hard to analyze exactly the effect of this change since speeding up the main reactor loop does not directly lead to a utilization drop: the main loop simply spins faster (things like reactor sleep are time based, not iteration based). However, for one test which involves a fair about of spinning this did seem to speed up the reactor loop by about 2%.

Reactor main loop optimziaton 

---

include/seastar/core/chunked_fifo.hh
include/seastar/core/metrics_api.hh
src/core/metrics.cc
src/core/prometheus.cc
src/core/scollectd.cc

The equivalent PR for upstream scylla is https://github.com/scylladb/seastar/pull/1741 
The vtools test passed CI as well https://github.com/redpanda-data/vtools/pull/1962
Large contiguous allocations may fail as the memory on a shard becomes fragmented over time. This can lead to over allocations on the metadata vector occurring at the call to vector.emplace_back():
```cpp
void impl::update_metrics_if_needed() {
if (_dirty) {
_metadata = ::seastar::make_shared<metric_metadata>();
auto mt_ref = ::seastar::make_shared<metric_metadata>();
auto &mt = *(mt_ref.get());
mt.reserve(_value_map.size());
_current_metrics.resize(_value_map.size());
size_t i = 0;
for (auto&& mf : _value_map) {
metric_metadata_vector metrics;
_current_metrics[i].clear();
for (auto&& m : mf.second) {
if (m.second && …
```

metrics: change metadata vector to chunked_fifo

---

include/seastar/coroutine/maybe_yield.hh

maybe_yield_awaiter resumes the coroutine (after it decided to suspend it) by scheduling *itself* as a task, which -- when executed -- resumes the coroutine.
The awaiter itself is (usually) allocated inside the coroutine frame, and dies after its containing co_await expression is resumed. This is a problem, because the reactor expects tasks to stay alive while they are running. To facilitate current_tasktrace(), a global pointer to the currently running task is needed. Thus, when the reactor starts executing a task, it saves a pointer to it in reactor::_current_task.
Since the awaiter task dies immediately after returning control to its parent, reactor::_current_task is left pointing to some garbage in the coroutine frame and current_tasktrace() will (most likely) segfault when used …

coroutine: fix a use-after-free in maybe_yield

---

include/seastar/core/semaphore.hh
tests/unit/semaphore_test.cc

When semaphore_units are (move-) reassigned with
other units, the held units aren't currently
returned to the semaphore. Call return_all
before reassigning the semaphore_units object.
Add a unit test reproducer.
Fixes #1465
Signed-off-by: Benny Halevy <bhalevy@scylladb.com>
(cherry picked from commit c4733e50ba0714e3ae4ee69c6e33a956cfce79ed)

semaphore: semaphore_units: return all units when reassigned

---

src/core/reactor_backend.cc

Using the epoll backend and having a non-closed socket that got terminated
with either EPOLLHUP|EPOLLERR under the hood but isn't closed yet can lead to
busy spinning in the reactor at 100%.
It's caused by the following scenario:
- epoll_pwait returns an event for a socket with EPOLLIN|EPOLLHUP (or
EPOLLOUT in a different respective case)
- We enter the error branch and set evt.events. This doesn't make much
difference at this point as pfd->events_requested is still equal to
EPOLLIN
- events_to_remove is calculated to 0
- complete_epoll_event is called setting pfd->events_requested to 0
- The loop concludes without removing the socket from the epoll set as
we calculate events_to_remove before changing it. I think this is
intended to avoid unneeded syscalls in the good case (so usually …

epoll: Avoid spinning on aborted connections

---

include/seastar/net/tls.hh
src/net/tls.cc

This commit extends the `tls::wrap_client` interface with an optional param which indicates to the sessions that it should not wait for an EOF after sending the BYE message.
Badly behaved servers will not send the expected EOF message. Clients that call `wait_input_shutdown` on the connected socket will hang for 10 seconds in that case.
The previous default behaviour has been preserved and clients should always wait for EOF if the intend to re-use the connection.
Upstream seastar PR [here](https://github.com/scylladb/seastar/pull/1797) was approved, so let's wait for that to merge and cherry pick from there.

tls: Optionally skip client EOF wait

---

src/core/smp.cc

Backport from upstream seastar.
Fixes multi-reactor support in same process by making making semaphore unique to reactor.

backport fix for multi-reactor

---

include/seastar/http/exception.hh
include/seastar/http/httpd.hh
src/http/httpd.cc

reply was moved to http::reply namespace, this pr fixes some params that were not changed and were triggering a deprecation message

http: fix deprecated warning, reply -> http::reply

---

include/seastar/core/posix.hh
include/seastar/http/request.hh
include/seastar/net/api.hh
include/seastar/net/stack.hh
src/http/httpd.cc
src/net/native-stack-impl.hh
src/net/posix-stack.cc
src/net/stack.cc
src/net/tls.cc
tests/unit/loopback_socket.hh

There is a need to know where an HTTP request originated from and what local address it arrived on.  This PR addresses this by adding `client_address` and `server_address` fields to the `http::request` structure.  This also adds in the infrastructure necessary to get the client address from the underlying connection.

httpd: Added server and client addresses to request structure

---

include/seastar/net/tls.hh
src/net/tls.cc
tests/unit/tls_test.cc

Required for https://github.com/redpanda-data/redpanda/pull/13477
Referenced by https://github.com/oleiman/vtools/tree/seastar-bump-tls_certs

tls: Add certificate_credentials to reload_callback

---

include/seastar/net/tls.hh
src/net/tls.cc
tests/unit/tls_test.cc

This reverts commit ab57ab6fe980420054bf94dd54d86c36f70c5d18, reversing changes made to c83e0172983753c61fa7361262e5f12a91eeacea.
This change broke one of the TLS unit tests (`tls_test.cc::test_reload_broken_certificates`) - an unhandled exception diverted control from the reload callback, causing a continuation in the test to block indefinitely.

Revert "Merge pull request #75 from oleiman/tls_cert_creds"

---

include/seastar/net/api.hh
include/seastar/net/tls.hh
src/net/tls.cc
tests/unit/tls_test.cc

This PR introduces an alternative reload callback for reloadable certificate credentials to provide the current `net::tls::certificate_credentials` to the callback receiver.
Also introduces a couple of accessors for same to expose access to serial numbers and expiration times for loaded certs and CAs.
Corresponds to https://github.com/scylladb/seastar/pull/1854

Expose TLS certificate details

---

include/seastar/core/metrics.hh
include/seastar/core/metrics_api.hh
include/seastar/core/metrics_registration.hh
src/core/metrics.cc

Extends the metrics api to allow changing the aggregation labels of a metrics family.
Otherwise one had to un-register every single metric instance in a metric family and then re-register with the changed aggregation labels.
For metric families with thousands of instances (e.g.: histograms with lots of different labels) this is quite expensive.
With this change we avoid the full reconstruction of the metrics family and all its metrics. Only the work associated with marking the metrics `dirty()` is needed then.

metrics: Add update_aggregate_labels()

---

include/seastar/net/api.hh
src/net/tls.cc

GnuTLS provides serial numbers not as a legible string of hex digits but as a byte array corresponding to an integer value up to 20 octets wide. The cert_info interface should reflect this.
To that end, this commit updates the type of `cert_info::serial` to an non-null-terminated basic_sstring of uint8_t.

net/tls: Adjust type for cert_info.serial

---

src/net/tls.cc

In Redpanda we were seeing surprisingly large overhead from running with
TLS enabled.
After some debugging we found that this is partly caused by doing an
excessively larger amount of `sendmsg` syscalls compared to when using
plain TCP.
This is caused by the implementation of `tls::session::put` which loops
over each fragment in the passed `net::packet` and treats it separately.
This will result in a call to `gnutls_record_send` for each fragment in
the packet (and consequently a call to `sendmsg` for each fragment via
the vector push function).
This can cause excessive overhead for `net::packets` which represent a
"packet" wrapped by header, trailer etc. In redpanda we were seeing
about 3-4 fragments per packet and hence the same factor of overhead in
terms of `sendmsg` syscalls.
To …

tls: linearize small packets on send

---

src/core/reactor_backend.cc
src/core/reactor_backend.hh

There is a potential crash in the `seastar::aio_general_context`. For more background see https://github.com/scylladb/seastar/issues/1784
We have now hit this in production so we should cherry pick the suggested fix from https://github.com/scylladb/seastar/pull/1788

Fix "seastar::aio_general_context::flush(): Assertion `clock::now() < retry_until'"

---

src/core/reactor_backend.cc
src/net/tls.cc

Update two of our patches as per upstream.
There is no real functional difference.

[v23.3.x] Pull in upstream versions of TLS & epoll changes

---

src/core/memory.cc

In one place in the memory sampling code we assume a non-null pointer
but if the system is out of memory this pointer may be null.
When using abort-on-bad-alloc this scenario is extremely unlikely since
the first failed allocation would have to meet very specific conditions
for this to occur: be a small allocation and be sampled, which is
unlikely since larger allocations usually fail first (and small pools
ask the underlying allocator for at most 128K at a time).
Discovered while analyzing https://github.com/redpanda-data/redpanda/issues/15711.

Fix edge case in memory sampler at OOM

---

src/core/reactor_backend.cc

Backport https://github.com/scylladb/seastar/pull/2123
When encountering an `io_submit` error in the `storage_context` we call `handle_aio_error` to handle said error.
First we check for `EAGAIN` and `EBADF` and handle those separately. For other errors we would call `throw_system_error_on` to throw an exception.
This was bugged because `throw_system_error_on` reads errno directly which means it might potentially print the wrong error code as errno might have changed from the error code that we passed to `handle_aio_error`. This can happen in the aio systemcall fallback thread where the io_submit error is handled only later after possibly suspending.
To fix this we just throw an exception in `handle_aio_error` directly and pass the correct error code.
`throw_system_error_on` checks for a …

reactor: Print correct errno on io_submit failure

---

include/seastar/http/common.hh
include/seastar/http/request.hh
include/seastar/http/url.hh
src/http/request.cc
src/http/url.cc
tests/unit/httpd_test.cc

Some REST APIs of Redpanda were incorrectly using the `url_decode` method to decode path parameters. This caused issues for Redpanda's clients as they were unable to delete users that had a '+' in the username. As part of solving the decoding, I introduced a `path_decode` method, and it would be most convenient if this method lived next to the existing `url_decode` utility method that `seastar` provides both to enable code reuse and to bring it to users' attention that they should make a conscious choice between the two decode methods.
Therefore, this PR ports this `url_decode` method over to the `seastar` library.
Related PR: https://github.com/redpanda-data/redpanda/pull/16694

http/util: add path_decode method

---

include/seastar/core/internal/timers.hh

Followup to #48 
Spotted with Clang 18

core/internal/timers: Add  timers missing include

---

demos/tls_echo_server.hh
src/net/ossl.cc

Adds support for mTLS clients. This works by setting invoking the `set_client_auth` field to `REQUIRED`. 
Also implemented the ossl analogue to the original `session::verify` method, which parses the subject and issuer from the cert checking for validity and optionally returning that info via a preregistered callback (`set_dn_callback`)
https://github.com/redpanda-data/core-internal/issues/1091

Add mTLS auth to the TLS implementation backed by OpenSSL

---

include/seastar/net/tls.hh
src/net/tls.cc
tests/unit/tls_test.cc

Passed up to application code as a tls::blob (basic_string_view<char>).
Also provide the ability to fetch this blob directly via credentials_builder::get_trust_file_blob()
Updates unit tests to accommodate the new reload callback signature.
Required for https://github.com/redpanda-data/redpanda/pull/17539

tls: Include trust file contents with reload callback

---

CMakeLists.txt
demos/tls_echo_server.hh
demos/tls_echo_server_demo.cc
demos/tls_simple_client_demo.cc
src/net/ossl.cc
src/net/tls-impl.cc
tests/unit/CMakeLists.txt
tests/unit/tls_test.cc

This pull request adds support for clients, meaning calls to `tls::connect` will return a client that is able to communicate over mTLS with a server. Due to this , the seastar unit tests (`test_tls.cc`) can now be run, as they start the homegrown client and server and use them to communicate with eachother.
Other additional fixes include:
- Enable use of cipher priority strings
- Ensuring any exceptions will permanently fault the connection (akin to logic in the GnuTLS impl)
- Fixing a bug with SSL shutdown
- Fixing a bug with sending/receiving data that only was observed with large payloads
- Handling the SSL_WANT_READ/WRITE error codes in all edge cases
- Fixing the tls client/server demo programs to establish mTLS connections

Supports for TLS clients within the OpenSSL TLS implementation

---

include/seastar/core/internal/cpu_profiler.hh
src/core/cpu_profiler.cc
tests/unit/cpu_profiler_test.cc

Add the ability to disable the CPU profiler in regions with known
issues. Specifically for Redpanda this is to disable stacktraces
while Wasmtime is running, as JIT doesn't generate stack trace
entries (for other reasons).
[CORE-486](https://redpandadata.atlassian.net/browse/CORE-486)
[CORE-486]: https://redpandadata.atlassian.net/browse/CORE-486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

core/cpu_profiler: add danger zone escape hatch

---

include/seastar/http/exception.hh
src/http/routes.cc

This PR adds `redirect_exception::to_reply()` for construction of a `http::reply` from a redirect case, with a `Location` header and optionally a `Retry-After` header.
Redpanda PR https://github.com/redpanda-data/redpanda/pull/17947 depends on this change.

http: `to_reply()` from `redirect_exception`

---

include/seastar/http/exception.hh
src/http/routes.cc

Backport of PR: https://github.com/redpanda-data/seastar/pull/107
This PR made its way into 24.1.x , backporting to v24.2.x

Backport PR #107 new `to_reply()` method from http exception

---

include/seastar/net/tls.hh

- Redpanda is failing to compile due to formatter<string_view>::format being SFINAE'd away.
- As a temporary fix, replacing call to ::format with ::format_to to resolve the compilation error

Temporarily replace call to formatter<string_view>

---

include/seastar/net/api.hh
src/net/tls.cc

char_traits<unsigned> is deprecated in LLVM 18, slated for removal in LLVM 19. Therefore remove this non-standard usage from cert_info.
Extracting the x509 serial number is a relatively infrequent operation and the result is always <= 20B, so the cost of using a vector here should be marginal.

net/tls: Replace cert_info::bytes with vector<byte>

---

include/seastar/net/tls.hh
src/net/ossl.cc
src/net/tls-impl.cc
tests/unit/tls_test.cc

GnuTLS allows for setting priority and server precedence all through the GnuTLS priority system.  OpenSSL on the other hand, has different APIs to handle this.
- To set server precedence in GnuTLS, simply provide the string %SERVER_PRECEDENCE in the priority string.  For OpenSSL, the flag SSL_OP_CIPHER_SERVER_PREFERENCE must be passed to SSL_CTX_set_options
- GnuTLS's priority string can be used to set the priority for all versions of TLS.  For OpenSSL, to set the ciphers available in TLSv1.2 and below, the user must call SSL_CTX_set_cipher_list. For TLSv1.3, the call is SSL_CTX_set_ciphersuites
As the format of the cipher/priority strings are different between OpenSSL and GnuTLS, the user of Seastar would have to change their code in order to change the format to match the requirements …

[CORE-2426] tls: Added new functions to support OpenSSL

---

include/seastar/net/tcp.hh
src/CMakeLists.txt
src/net/tls-impl.cc
src/websocket/server.cc

Fix ups to fix gcc11 compiler errors

Final fixups for ossl

---

src/net/ossl.cc

The difference between `X509_V_FLAG_CRL_CHECK` and `X509_V_FLAG_CRL_CHECK_ALL` is that without the `_ALL` flag, only the leaf certificate and not the whole chain will be checked for revocation.

net: Added X509_V_FLAG_CRL_CHECK_ALL flag

---

pkgconfig/seastar.pc.in

When compiling for OpenSSL, have the pc file select openssl >= 3.0.0 rather than GnuTLS.

pkgconfig: Updated seastar.pc.in for OpenSSL build

---

src/net/ossl.cc
tests/unit/CMakeLists.txt
tests/unit/tls_test.cc

GnuTLS permitted a user to provide a chain of certificates in the certificate file passed to set_x509_key_file rather than set_x509_trust_file.  This commit adjusts how the OpenSSL implementation parses the provided certificate file so it can also accept a chain of certs in the certificate file parameter to set_x509_key_file.

CORE-5546 support chain in key cert pair

---

include/seastar/net/dns.hh
src/net/dns.cc

In case user applications wish to examine and react to specific DNS errors, make `ares_error_category` accessible via
`seastar::net::dns::error_category()` in a similar fashion to `seastar::tls::error_category()`.
Signed-off-by: Michael Boquard <michael@redpanda.com>
(cherry picked from commit 20d4775affde67024dd73178587f127d6cf87788)

[v24.1.x] net: Expose DNS error category

---

include/seastar/net/dns.hh
src/net/dns.cc

In case user applications wish to examine and react to specific DNS errors, make `ares_error_category` accessible via
`seastar::net::dns::error_category()` in a similar fashion to `seastar::tls::error_category()`.
Signed-off-by: Michael Boquard <michael@redpanda.com>
(cherry picked from commit 20d4775affde67024dd73178587f127d6cf87788)

[v23.3.x] net: Expose DNS error category

---

src/core/prometheus.cc
tests/unit/CMakeLists.txt
tests/unit/prometheus_test.cc

Follow up fix to https://github.com/redpanda-data/seastar/pull/136
Fixes up an earlier commit which should have been a refactor commit but had an unintended change to the way `double`'s were formatted on the prometheus response.
This unintended change was caught by the redpanda test suite indirectly (some test expectations were looking for a specific metric value which they could not find because the value got rounded to a different number in scientific notation). We now also add a test around the prometheus wire formatting to catch such bugs earlier inside the codebase.

prometheus: fix double formatting to stringstream 

---

include/seastar/net/tls.hh
src/net/ossl.cc
src/net/tls-impl.cc
src/net/tls-impl.hh
src/net/tls.cc
tests/unit/tls_test.cc

This PR cherry-picks a number of commits from upstream to help ensure a smaller divergence.
What is important is the first commit that adds support for TLS1.3 session tickets.
**IMPORTANT**
This _does not_ implement session resumption in OpenSSL.  A follow on change will implement this feature.  The Seastar TLS unit test will fail when built using OpenSSL.

CORE-6796 apply upstream changes for TLS

---

include/seastar/core/reactor.hh
include/seastar/net/api.hh
src/core/reactor.cc
src/core/reactor_backend.cc
tests/unit/socket_test.cc

Downstream: 
- https://github.com/scylladb/seastar/pull/2458
- https://github.com/scylladb/seastar/pull/2390

Downstream steal and TCP buf fixes

---

include/seastar/core/deleter.hh
include/seastar/core/temporary_buffer.hh

Seastar's `deleter` is used in `temporary_buffer` and a couple of other classes. By making the reference counting in it atomic we make sharing `temporary_buffer`s in a read-only manner across shards safe.

core: make reference counting in `deleter` atomic

---

include/seastar/core/temporary_buffer.hh

`hdr_hist` uses the method to make a raw buffer a temporary_buffer

Add `hdr_hist` to `temporary_buffer`'s friends

---

include/seastar/core/reactor.hh
src/core/reactor.cc

A possible issue with how Docker Desktop v4.34+ (particulary on macOS) handles `pidfd` functionality causes an assertion failure in Seastar's `reactor::waitpid` method.
The issue:
- Seastar creates a `pidfd` using `pidfd_open`
- It polls this file descriptor until it becomes readable
- When readable, call `waitpid` with `WNOHANG`.  According to [pidfd_open](https://man7.org/linux/man-pages/man2/pidfd_open.2.html), the file descriptor becomes readable when the process terminates
- Seastar expects `waitpid` to either return a positive integer representing the child process that has ended or a negative value to indicate an error.  However if `waitpid` returns `0`, then Seastar asserts, crashing the using application.
This change introduces retry logic when using a `pidfd` and removes the …

reactor: Always retry waitpid

---

src/net/ossl.cc

When there is an error while trying to write to the underlying socket
inside the bio write method, we should signal that error by propagating
it on openssl's internal error stack rather than through setting errno.
Using the error stack is openssl's conventional way of communicating
errors, so we should use it instead of relying on `errno`. Writing to
`errno` is problematic because it may be read by other parts of the
system and this "poisoning" of the global errno variable could cause
unexpected errors inside other parts of the system.
The issue arises from the OpenSSL error stack not being cleared when a system error occurs, such as an EPIPE error when the remote end closes the connection. If the error stack is not purged, subsequent TLS operations may fail due to the lingering error.
In …

net: avoid propagating openssl system errors to errno 

---

src/net/ossl.cc

Manual backport of https://github.com/redpanda-data/seastar/pull/153
When there is an error while trying to write to the underlying socket
inside the bio write method, we should signal that error by propagating
it on openssl's internal error stack rather than through setting errno.
Using the error stack is openssl's conventional way of communicating
errors, so we should use it instead of relying on errno. Writing to
errno is problematic because it may be read by other parts of the
system and this "poisoning" of the global errno variable could cause
unexpected errors inside other parts of the system.
The issue arises from the OpenSSL error stack not being cleared when a system error occurs, such as an EPIPE error when the remote end closes the connection. If the error stack is not purged, …

[v24.2.x] net: avoid propagating openssl system errors to errno

---

include/seastar/core/when_all.hh

since [P1413R3](https://wg21.link/p1413r3) was accepted by C++23, std::aligned_union_t was deprecated in this standard. so let's be prepared for this. as suggested by the proposal, we are replacing `std::aligned_union_t` with an array of `std::byte`.

when_all: stop using deprecated std::aligned_union_t

---

src/net/ossl.cc

When compiling Seastar with Redpanda's bazel build system, asserts are compiled out.  This led to a segmentation fault when using TLS in unit tests.

tls: Do not place functional code in assert

---

apps/io_tester/io_tester.cc
include/seastar/core/metrics_api.hh
src/core/metrics.cc
src/core/prometheus.cc
src/core/scollectd.cc
tests/unit/metric_family_replication_test.cc
tests/unit/metrics_test.cc
tests/unit/rpc_test.cc

Downstream:
- https://github.com/scylladb/seastar/pull/2554
- https://github.com/scylladb/seastar/pull/2561
With some adjustments for all the other metric changes we have.

Downstream metrics improvements

---

include/seastar/net/tls.hh
src/net/ossl.cc
src/net/tls-impl.cc

TLS client renegotiation was removed in TLSv1.3 due to vulnerabilities found in the protocol.  For safety reasons, it is by default disabled, however an option is provided to re-enable it if desired.

tls/ossl: Added option to enable TLS renegotiation

---

tests/unit/cpu_profiler_test.cc

Until we can fix them.
See CORE-9144.

cpu_profiler: disable two tests which are hanging

---

CMakeLists.txt
src/core/thread.cc

It causes problems with longjmp
*** longjmp causes uninitialized stack frame ***: terminated
Aborting on shard 0.
Backtrace:
which was taken care of in the cmake build, but needs to be fixed in our bazel build. reference: scylladb/seastar#2344
Closes #2522
(cherry picked from commit c96444fbe43acac0d31418b65b04395c11fdda14)

thread: do not use fortify source

---

include/seastar/core/internal/cpu_profiler.hh
src/core/cpu_profiler.cc
tests/unit/cpu_profiler_test.cc
tests/unit/stall_detector_test_utilities.hh

Capture the scheduler group running at the moment a sample is taken, so we can expose this in the profile json.

Add scheduler group to cpu profiler

---

CMakeLists.txt
cmake/CheckP2582R1.cmake
include/seastar/rpc/rpc_types.hh

Downstream https://github.com/scylladb/seastar/pull/2446 to fix the gcc build

build: check for P2582R1 support

---

.github/workflows/test.yaml
install-dependencies.sh
src/net/ossl.cc
tests/unit/CMakeLists.txt
tests/unit/tls_test.cc

Fixes: CORE-9178
This addresses a possible race condition that some customers have witnessed where Seastar was not returning the correct certificate and this caused authorization failures on the broker. The fix is to use the correct OpenSSL API (SSL_get1_peer_certificate) rather than the cert held by the callback.
Note: We will backport this to v24.3 and v24.2 to address this bug in all OpenSSL implementations

Tls cert race/core 9178/v25.1.x

---

install-dependencies.sh
src/net/ossl.cc
tests/unit/CMakeLists.txt
tests/unit/tls_test.cc

Backport of https://github.com/redpanda-data/seastar/pull/175
Fixes: CORE-9180
Conflict in 6ccfd1fbe04dac45aed1b32ad3fffe1b83018032:
* github workflows not in use by this branch
* Updated install-dependencies and updated commit message

Tls cert race/core 9179/v24.3.x

---

install-dependencies.sh
src/net/ossl.cc
tests/unit/CMakeLists.txt
tests/unit/tls_test.cc

Backport of #175 
Fixes: CORE-9180
Conflict in 321e67c44707d46dd510d3a815ccdb11107163d1:
* github workflows not in use by this branch
* Updated install-dependencies and updated commit message

Tls cert race/core 9180/v24.2w.x

---

cooking_recipe.cmake
src/CMakeLists.txt
src/core/memory.cc

Seastar is currently pulling in all of libnuma to just invoke a single syscall. Additionally since libnuma being LGPL licensed, it's simpler to not include it as a dependency. Replace the call in numaif.h with a direct syscall.
I'm assuming that once libnuma was depended on because it was a dependency of hwloc, however, hwloc version 2 removed the dependency on libnuma, so Seastar can too:
https://github.com/open-mpi/hwloc/blob/263908a2c1f21c0e221a8d1f6472daf3a1fc07b9/NEWS#L291
(cherry picked from commit 8ab0267117de9f0a0dabfeb0fd54227a428eefe1)

memory: remove libnuma dependency

---

include/seastar/net/tls.hh
src/net/ossl.cc
src/net/tls-impl.cc
src/net/tls-impl.hh
src/net/tls.cc
tests/unit/tls_test.cc

Added a dn_format flag to switch between legacy and RFC2253 format. Legacy format matches that originally returned by the GnuTLS api `gnutls_x509_crt_get_dn` which returns the DN in the format of `C=US,ST=London,L=London,O=Redpanda Data,OU=Core,CN=id`.  RFC2253 format, effectively reverses the order: `CN=id,OU=Core,O=Redpanda Data,L=London,ST=London,C=US`.
Note: We will backport this to v24.3 to make available for customers.
Fixes: CORE-9265

tls: Added support for fetching DN in RFC2253 format

---

src/core/metrics.cc

Pass the handle such that we internalize in the right metric impl.
This shouldn't matter that much as it's just another map that things get stored in but it's more correct like that.

metrics: Internalize in the proper impl

---

.github/workflows/tests.yaml

Seastar has a C++20 modules variation of the build in GHA, but our changes have left it quite broken as we don't use modules.
Disable this build for now so we can get the build green and protect the seastar branch.

GHA: disable modules build

---

src/core/reactor.cc

Downstream https://github.com/scylladb/seastar/pull/2715

reactor: Disable hot polling if wakeup granularity is too high

---

src/core/app-template.cc

We print a warning when SEASTAR_DEBUG is enabled, saying it's not for production or performance testing. This might be a suitable warning for the application itself to emit, but a framework like seastar should leave that choice up to the application. This warning cannot be supressed and does not follow the normal logging system, so it is unnecessarily noisy and interferes with anything which parses stderr.
(cherry picked from commit 5ee7dee7c75deac59ee3e3e518662101c67fe40e)

app-template: remove production warning

---

src/core/reactor.cc
tests/unit/stall_detector_test.cc

This downstreams most of the updates and fixes related to CORE-9596:
Diagnostic upgrades (accepted upstream):
https://github.com/scylladb/seastar/pull/2691
https://github.com/scylladb/seastar/pull/2727
Crash fix (not accepted upstream yet):
https://github.com/scylladb/seastar/pull/2714
I did not downstream one diagnostic fix (accepted upstream) because it does not merge cleanly due to earlier changes to the stall notifier which are not yet in our fork:
https://github.com/scylladb/seastar/pull/2712
We will get this fix when we rebase on steastar master.
I plan to backport these to at least 24.2.

Downstream stall notifier fixes

---

src/core/reactor.cc

Downstream https://github.com/scylladb/seastar/pull/2715 to 25.1

[v25.1.x] reactor: Disable hot polling if wakeup granularity is too high 

---

src/net/ossl.cc

Prior to this commit, in certain situations, the put() and get() methods would 'drop into' handshake() if they determined that a re-negotiation was occurring.  This was unecessary as OpenSSL provides helpful error codes like SSL_WANT_READ and SSL_WANT_WRITE which indicates if OpenSSL needed to send/receive non-user data to handle re-negotiations.
This may have also led to a rare situation where the put() method would assert because the _output_pending future had not resolved.  This change properly handles the SSL_WANT_READ and SSL_WANT_WRITE conditions and ensures that the _output_pending future resolves.

tls/ossl: Improved handling of OpenSSL error conditions

---

src/net/ossl.cc

NOTE: Backport of https://github.com/redpanda-data/seastar/pull/215
Prior to this commit, in certain situations, the put() and get() methods would 'drop into' handshake() if they determined that a re-negotiation was occurring.  This was unecessary as OpenSSL provides helpful error codes like SSL_WANT_READ and SSL_WANT_WRITE which indicates if OpenSSL needed to send/receive non-user data to handle re-negotiations.
This may have also led to a rare situation where the put() method would assert because the _output_pending future had not resolved.  This change properly handles the SSL_WANT_READ and SSL_WANT_WRITE conditions and ensures that the _output_pending future resolves.
(cherry picked from commit 604293e28b301221fe16f648cb61a8f3aa77af0b) (cherry picked from commit …

[v24.3.x] tls/ossl: Improved handling of OpenSSL error conditions

---

src/net/ossl.cc

NOTE: Backport of #215 
Prior to this commit, in certain situations, the put() and get() methods would 'drop into' handshake() if they determined that a re-negotiation was occurring.  This was unecessary as OpenSSL provides helpful error codes like SSL_WANT_READ and SSL_WANT_WRITE which indicates if OpenSSL needed to send/receive non-user data to handle re-negotiations.
This may have also led to a rare situation where the put() method would assert because the _output_pending future had not resolved.  This change properly handles the SSL_WANT_READ and SSL_WANT_WRITE conditions and ensures that the _output_pending future resolves.
(cherry picked from commit 604293e28b301221fe16f648cb61a8f3aa77af0b)

[v25.1.x] tls/ossl: Improved handling of OpenSSL error conditions

---

.github/workflows/alpinelinux.yaml
include/seastar/util/backtrace.hh
src/core/reactor.cc
src/util/backtrace.cc
tests/unit/cpu_profiler_test.cc
tests/unit/stall_detector_test_utilities.hh

guarded_backtrace has a static local mutex but was in an anonymous namespace, which is unsafe as each translation unit would have its own instance.
Move it to the .cc file (it's happier there anyway) and remove the anonymous namespace.
Also fix the alpine build by only building this is execinfo is available.

various Alpine fixes

---

src/util/log.cc

We notice that assertion messages are not being printed as expected.
In these cases you simply see a message like (libc++):
```
libc++abi: terminating
Aborting on shard 0, in scheduling group main.
Backtrace:
```
libstd++ is similar:
```
terminate called without an active exception
Aborting on shard 0, in scheduling group main.
Backtrace:
```
Underlying cause is that we print to stdout, and stdout is not explicitly flushed. In cases where stdout is not line buffered, we will close the message (so e.g., when the output is piped or redirected).
We should (a) assert to stderr, not stdout, and (b) flush the stream.
This is in line with libc and the C++ standard (though it specifies that abort() is called, not std::terminate()).
(cherry picked from commit …

SEASTAR_ASSERT: assert to stderr and flush stream
